<a href="https://colab.research.google.com/github/paras2003gupta/Machine_learning_google_colab/blob/main/Jovian1(NUMPY).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#we have climate data and we have to predict growth of apple in that area.
#yeild_of_apple= w1*temp+w2*rainfall+w3*humidity
w1,w2,w3 = 0.3,0.2,0.5
kento_temp = 73
kento_rainfall = 67
kento_humidity = 43
kento_yield_of_apple = w1*kento_temp+w2*kento_rainfall+w3*kento_humidity
print("The expected value og yeild of appleas are {} tons per hectare".format(kento_yield_of_apple))

The expected value og yeild of appleas are 56.8 tons per hectare


In [ ]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [ ]:
weights = [w1,w2,w3]
def crop_yeild(region,weights):
    result = 0
    for x,w in zip(region,weights):
        result += x*w

    return result

In [ ]:
crop_yeild(kanto,weights)


56.8

In [ ]:
crop_yeild(hoenn,weights)

81.9

In [ ]:
#Now Using NUMPY and convert list to numpy
kanto = np.array(kanto)
weights = np.array(weights)
kanto, weights

(array([73, 67, 43]), array([0.3, 0.2, 0.5]))

In [ ]:
#used to apply dot product
ans = np.dot(kanto,weights)
print(ans)
type(weights)

56.8


numpy.ndarray

In [ ]:
(kanto * weights).sum()

56.8

In [ ]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))
#numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

CPU times: user 212 ms, sys: 1.88 ms, total: 214 ms
Wall time: 214 ms


833332333333500000

In [ ]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: user 3.08 ms, sys: 12 µs, total: 3.09 ms
Wall time: 3.63 ms


833332333333500000

In [ ]:
!pip install jovian


In [ ]:
import jovian

In [ ]:
jovian.commit(projext = 'numpy-live')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


In [ ]:
#multi-dimensional array
climate_data = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
])

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
climate_data.shape

(5, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
weights.shape

(3,)

In [ ]:
weights.dtype

dtype('float64')

In [ ]:
climate_data.dtype

dtype('int64')

In [ ]:
#in numpy arrays we can not use arrays as list only one type of datatype is allowed
arr3 = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],[[1,2,3],
    [4,5,6],
    [7,8,9.82]]
])
arr3.dtype

dtype('float64')

In [ ]:
print(arr3)

[[[1.   2.   3.  ]
  [4.   5.   6.  ]
  [7.   8.   9.  ]]

 [[1.   2.   3.  ]
  [4.   5.   6.  ]
  [7.   8.   9.82]]]


In [ ]:
climate_data


array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
ans = np.matmul(climate_data,weights)
print(ans)
print(np.shape(climate_data))
print(np.shape(weights))
print(np.shape(ans))
#

[56.8 76.9 81.9 57.7 74.9]
(5, 3)
(3,)
(5,)


In [ ]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
#Working with CSV files
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7dd6b6a5baf0>)

In [ ]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [ ]:
climate_data.shape

(10000, 3)

In [ ]:
yeilds = climate_data @ weights

In [ ]:
print(yeilds.shape)
print(yeilds)

(10000,)
[72.2 59.7 65.2 ... 71.1 80.7 73.4]


In [ ]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

In [ ]:
yeilds.reshape(10000,1)

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [ ]:
climate_results=np.concatenate((climate_data,yeilds.reshape(10000,1)),axis=1)

In [ ]:
np.savetxt('climate_results.txt',climate_results,fmt ='%.2f',delimiter = ",",header='temp,rainfall,humidity,yeild_apples',comments='')

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:

Mathematics: np.sum, np.exp, np.round, arithemtic operators
Array manipulation: np.reshape, np.stack, np.concatenate, np.split
Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
Statistics: np.mean, np.median, np.std, np.max

###Array Broadcasting
Numpy arrays also support broadcasting, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.



In [ ]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr4 = np.array([4, 5, 6, 7])
arr4.shape

(4,)

In [ ]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression arr2 + arr4 is evaluated, arr4 (which has the shape (4,)) is replicated three times to match the shape (3, 4) of arr2. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

alt
Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [ ]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [ ]:
arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [ ]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [ ]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.sum(arr1==arr2)
#this will tell ki kitne elements equal hain arr1 and arr2 mei element wise

3

In [ ]:
(arr1==arr2).sum()

3

In [ ]:
#indexing and slicing in python multidimentsion list
arr3 = np.array([
    [[11, 12, 13, 14],
     [13, 14, 15, 19]],

    [[15, 16, 17, 21],
     [63, 92, 36, 18]],

    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]])

In [ ]:
arr3.shape


(3, 2, 4)

In [ ]:
arr3[1,1,2]

36.0

In [ ]:
arr3[2,1,2]

19.5

In [ ]:
#subarray using range
arr3

In [65]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [66]:
#mixing indexes and ranges
arr3[1:,1,3]

array([18., 43.])

In [67]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [68]:
arr3[:2,1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [69]:
#other ways of creating nuympy arrays
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [73]:
 np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.random.rand(5)

array([0.94965201, 0.58255929, 0.05870459, 0.85480228, 0.49043831])

In [77]:
np.random.randn(2,3)

array([[ 0.85116577,  0.47009416,  0.8875189 ],
       [ 0.01401133, -0.69000684, -0.0723573 ]])

In [78]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [79]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])